### PR TITLE
Dataloader updates

### PR DESCRIPTION
**Pull request by daviswer**
Add tempfile-based dataloader unit tests from closed repo. 

Update StreamingDocDataset and PreloadBufferDataset for hygiene (no more repeated popping from long list, explicitly `del` expired readers)

Compress StreamingDocDataset's massive docset data structure into list of dataset/shard/(docid ranges)

Implement LCG-based random mapping as a pseudo-shuffle (since we're no longer materializing an ordered list of docids)

### CODE REVIEW

**Comment by lchu-ibm** [comment]
besides doc strings, we should write a github issue on this talking about the change. 

I will create one and link it back here.

**Comment by nairbv** [comment]
> (no more repeated popping from long list, explicitly del expired readers)

I'm not finding either of these changes in the diff, searching for "pop" or "del"

**Comment by lchu-ibm** [comment]
@nairbv Davis would need to update the PR description.

But in short, we found that none of the things we discussed/suspected mattered, that made zero difference on the perf. We did find the root cause and fixed it.  I am writing a github issue on it and will share.

**Comment by lchu-ibm** [comment]
@nairbv a quick draft here: https://github.com/foundation-model-stack/fms-fsdp/issues/70

**Comment by daviswer** [comment]
> > (no more repeated popping from long list, explicitly del expired readers)
> 
> I'm not finding either of these changes in the diff, searching for "pop" or "del"

My bad, not sure how those didn't make it in properly. Added!

**Comment by lchu-ibm** [comment]
@daviswer can you check the test failures?

**Comment by daviswer** [comment]
LCG is now properly stateful, as the stateless version was producing cyclical sawtooth patterns, and properly seeded and randomized across workers

**Review by lchu-ibm — APPROVED** [review]

**Pull request merged**
